// TODO: add necessary imports

import {useState, useEffect} from 'react';
import fetchData from '../utils/fetchData';

const MEDIA_API = import.meta.env.VITE_MEDIA_API;
const AUTH_API = import.meta.env.VITE_AUTH_API;
const UPLOAD_API = import.meta.env.VITE_UPLOAD_SERVER;

const useMedia = () => {
  // move medaiaArray state here
  const [mediaArray, setMediaArray] = useState([]);

  useEffect(() => {
    try {
      const getMedia = async () => {
        // 1. Hakee pelkän media datan
        const mediaData = await fetchData(MEDIA_API + '/media');

        //console.log('Fetched media data: ', mediaData);

        // Hake jokaiselle media itemille käyttäjä Promise.all hyödyntäen
        const newArray = await Promise.all(
          mediaData.map(async (item) => {
            const user = await fetchData(`${AUTH_API}/users/${item.user_id}`);

            // yhdistäkään user mediaData itemiin
            return {
              ...item,
              username: user.username,
            };
          })
        );
        setMediaArray(newArray);
      };
      getMedia();
    } catch (error) {
      console.error('Error fetching media data: ', error);
    }
  }, []); // Tyhjää dependency, joka ajetaan vain kerran

  const postMedia = async (fileData, inputs, token) => {
    // post the data to Media API and get the data as MediaResponse
    // return the data
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      // create a suitable object for Media API: without media_id,  user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
      body: JSON.stringify({...inputs, ...fileData}),
    };

    const mediaResponse = await fetchData(MEDIA_API + '/media', fetchOptions);
    return mediaResponse;
  };

  const deleteMedia = async (id, token) => {
    const fetchOptions = {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
    };

    const deleteResponse = await fetchData(
      `${MEDIA_API}/media/${id}`,
      fetchOptions
    );
    return deleteResponse;
  };

  const modifyMedia = async (mediaId, inputs, token) => {
    const fetchOptions = {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(inputs),
    };
    return await fetchData(`${MEDIA_API}/media/${mediaId}`, fetchOptions);
  };
  return {mediaArray, postMedia, deleteMedia, modifyMedia};
};

const useAuthentication = () => {
  const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const loginResult = await fetchData(
      import.meta.env.VITE_AUTH_API + '/auth/login',
      fetchOptions
    );
    return loginResult;
  };
  return {postLogin};
};

const useUser = () => {
  const getUserByToken = async (token) => {
    const options = {
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    const tokenResult = fetchData(`${AUTH_API}/users/token`, options);
    return tokenResult;
  };

  const postUser = async (user) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(user),
    };
    const registerResult = await fetchData(
      import.meta.env.VITE_AUTH_API + '/users/',
      fetchOptions
    );
    return registerResult;
  };
  return {getUserByToken, postUser};
};

const useFile = () => {
  const postFile = async (file, token) => {
    // create FormData object
    const formData = new FormData();

    // add file to FormData
    formData.append('file', file);

    console.log(formData);
    // upload the file to file server and get the file data (url = import.meta.env.VITE_UPLOAD_SERVER + '/upload')
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
      },
      body: formData,
    };
    const uploadResponse = await fetchData(`${UPLOAD_API}/upload`, options);
    return uploadResponse;
  };
  return {postFile};
};

const useLikes = () => {
  const postLike = async (mediaId, token) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },

      body: JSON.stringify({media_id: mediaId}),
    };

    const likeResponse = await fetchData(MEDIA_API + '/likes', fetchOptions);
    return likeResponse;
  };

  const deleteLike = async (likeId, token) => {
    const fetchOptions = {
      method: 'Delete',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };

    const deleteResponse = await fetchData(
      `${MEDIA_API}/likes/${likeId}`,
      fetchOptions
    );
    return deleteResponse;
  };

  const getLikeCountByMediaId = async (mediaId) => {
    return await fetchData(`${MEDIA_API}/likes/count/${mediaId}`);
  };

  const getUserLike = async (mediaId, token) => {
    const fetchOptions = {
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };

    return await fetchData(
      `${MEDIA_API}/likes/bymedia/user/${mediaId}`,
      fetchOptions
    );
  };

  return {postLike, deleteLike, getLikeCountByMediaId, getUserLike};
};

export {useMedia, useAuthentication, useUser, useFile, useLikes};
